export default defineAppConfig({
  pages: [
    'pages/index/index',
    'pages/question-bank/index',
    'pages/profile/index',
    'pages/history/index',
    'pages/history-detail/index',
    'pages/wrong-book/index',
    'pages/wrong-book-detail/index',
    'pages/generating/index',
    'pages/topic-confirm/index',
    'pages/generate-fail/index',
    'pages/quiz/index',
    'pages/report/index',
    'pages/share/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#F8F9FE',
    navigationBarTitleText: 'AI炼金',
    navigationBarTextStyle: 'black',
    backgroundColor: '#F8F9FE',
  },
  tabBar: {
    custom: true,
    color: '#9AA5B8',
    selectedColor: '#7B61FF',
    backgroundColor: '#FFFFFF',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/index/index', text: '首页' },
      { pagePath: 'pages/question-bank/index', text: '题库' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ],
  },
})
